(deftheme pacodev
  "Created 2016-09-09.")

(custom-theme-set-faces
 'pacodev
 '(cursor ((t (:background "#F8F8F8"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((t (:foreground "#FBDE2D"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#61CE3C"))))
 '(font-lock-type-face ((t (:foreground "#FBDE2D"))))
 '(font-lock-variable-name-face ((t (:foreground "#F8F8F8"))))
 '(fringe ((t (:background "#2E3436"))))
 '(highlight ((t (:background "#253B76"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "coral4" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "indian red"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "dodgerblue1" :foreground "white"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "red1" :foreground "white"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 '(default ((t (:background "#071367" :foreground "#F8F8F8")))))

(provide-theme 'pacodev)
